title = "Dylan Pindur"
baseURL = "https://dpindur.github.io/"
languageCode = "en-us"
theme = "hyde"
pygmentsCodefences = true
pygmentsStyle = "dracula"

## Site Settings
[params]
    description = "Software & Security"
    themeColor = "theme-base-0d"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
